In [10]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
% matplotlib inline 

In [4]:
df=pd.read_csv("train.csv")

In [8]:
df

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  \
0           14.0          16.0          6.0       96.0          42.0   
1           11.0          20.0          5.0       70.0          31.0   
2           14.0          16.0          6.0       99.0          53.0   
3            9.0          17.0          6.0       31.0          16.0   
4           14.0          24.0          7.0       87.0          38.0   
5            6.0          11.0          4.0       90.0          47.0   
6           11.0          19.0          7.0       85.0          50.0   
7           14.0          13.0          6.0       40.0          15.0   
8            6.0           5.0          6.0       21.0           1.0   
9            3.0           3.0          4.0       53.0           1.0   
10          11.0           6.0          4.0       55.0          18.0   
11          14.0          23.0          8.0       97.0          57.0   
12          11.0           6.0          4.0       50.0          20.0   
13          11.0          16.0          6.0      102.0          56.0   
14          11.0          10.0          5.0       66.0          19.0   
15           2.0           3.0          6.0       54.0          41.0   
16          11.0          10.0          5.0       33.0          16.0   
17           4.0           6.0          3.0       47.0          10.0   
18          11.0          12.0          4.0       85.0          43.0   
19          11.0          10.0          4.0       48.0          18.0   
20          14.0          23.0          7.0       97.0          57.0   
21           2.0           1.0          6.0        3.0           1.0   
22          11.0          16.0          7.0       95.0          53.0   
23          13.0           0.0          4.0       70.0          31.0   
24          11.0           6.0          4.0       73.0          41.0   
25          11.0          23.0          7.0      103.0          56.0   
26          11.0          10.0          4.0       37.0          38.0   
27          11.0          23.0          7.0      103.0          58.0   
28          11.0          10.0          4.0       52.0          52.0   
29           0.0           3.0          3.0        0.0           1.0   
...          ...           ...          ...        ...           ...   
1430        14.0          14.0          4.0       97.0          50.0   
1431        13.0           9.0          5.0       70.0          31.0   
1432         0.0           5.0          3.0        0.0          56.0   
1433        14.0          14.0          5.0       87.0          38.0   
1434        11.0          11.0          4.0       74.0          28.0   
1435        11.0          10.0          5.0       50.0          50.0   
1436        11.0          10.0          3.0       26.0           2.0   
1437        11.0          23.0          7.0      110.0          58.0   
1438        11.0           5.0          5.0       52.0          51.0   
1439        14.0          13.0          6.0       58.0          23.0   
1440         9.0          17.0          5.0        7.0          54.0   
1441        13.0          16.0          5.0       85.0          43.0   
1442        14.0          19.0          9.0      110.0          58.0   
1443         0.0           3.0          5.0       42.0           1.0   
1444        11.0          16.0          6.0       85.0          43.0   
1445         7.0           6.0          5.0       62.0          22.0   
1446        11.0          11.0          4.0       50.0          20.0   
1447        14.0          16.0          7.0      105.0          51.0   
1448         6.0           4.0          3.0       11.0          38.0   
1449         1.0           0.0          4.0       33.0          16.0   
1450         4.0          10.0          4.0       78.0          30.0   
1451        11.0          19.0          7.0      110.0          59.0   
1452         1.0           4.0          4.0       97.0          50.0   
1453        11.0          11.0          4.0   

In [12]:
X = df.iloc[:,:23].values
X

array([[  14.,   16.,    6., ...,    1.,    2.,  548.],
       [  11.,   20.,    5., ...,    1.,    2.,  460.],
       [  14.,   16.,    6., ...,    1.,    2.,  608.],
       ..., 
       [   9.,   17.,    6., ...,    1.,    1.,  252.],
       [  11.,   10.,    4., ...,    0.,    1.,  240.],
       [  11.,    4.,    4., ...,    2.,    1.,  276.]])

In [15]:
y = df.loc[:,["SalePrice"]].values
y

array([[ 208500.],
       [ 181500.],
       [ 223500.],
       ..., 
       [ 266500.],
       [ 142125.],
       [ 147500.]])

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [26]:
from sklearn.linear_model import LinearRegression
Ir=LinearRegression()

In [27]:
Ir.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
Ir.intercept_

array([-64685.79170598])

In [29]:
Ir.coef_

array([[  3.33266101e+02,   1.72907758e+03,   8.71588990e+03,
         -5.74394723e+01,   1.44350854e+02,  -4.12478664e+03,
          3.40418773e+01,   7.90795412e+03,  -1.78572908e+03,
          1.25745168e+04,   2.74237056e+01,   1.07678865e+03,
          5.52326905e+00,   4.56570443e+01,  -5.90584040e+03,
          1.09974078e+04,   1.06197024e+03,   8.67046293e+03,
         -3.27680685e+01,   7.86200253e+01,   2.91883315e+03,
          6.40828939e+03,   1.29921921e+01]])

In [31]:
Ir.score(X_test, y_test)

0.76056505809653552